### ISSUE TITLE
Github Workflows improve environment calling

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#142]
There should be a way to define a single matrix of variables that will then be used by multiple workflows. 

My github actions fu isn't as great as I want it to be, but the current setup is quite error prone, as we're copying the same "matrix" over multiple times.

**Comment by brownoxford** [comment]
Quick review of the Github docs did not yield a solution, but I agree this would be less error prone if possible.

**Comment by mkhraisha** [comment]
I think theres a thing you can do it with this: https://docs.github.com/en/actions/using-workflows/reusing-workflows, and calling the workflows from another one

**Comment by mkhraisha** [comment]
I think something like this would work:

in a `master workflow`:
define matrix of companies
call a reusable workflow with that matrix's data,
```
Master workflow
jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      username: mona
    secrets:
      genericCompanyVariable: ${{ companyMatrixValue }}
```

``` 
Reusable Flow

\\ rest of file
env: 
genericCompanyVariable: genericCompanyVariable
```
