### ISSUE TITLE
Add more definition to credential status request body

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#358]
Currently, the OpenAPI definition for the request body of `/credentials/status` is rather loose. This issue proposes that we restrict the definition a bit to make expectations clearer and testing easier.

[Current schema](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/credential-status.yml):
```yaml
        schema:
          type: object
          description: Request for updating the status of an issued credential.
          properties:
            credentialId:
              type: string
            credentialStatus:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
```

Proposed Schema:

```yaml
        schema:
          type: object
          description: Request for updating the status of an issued credential.
          required:
            - credentialId
            - credentialStatus
          properties:
            credentialId:
              type: string
            credentialStatus:
              type: array
              maxItems: 1
              items:
                type: object
                required:
                  - type
                  - status
                properties:
                  type:
                    type: string
                    enum: ['RevocationList2020Status']
                  status:
                    description: Use a value of 0 (zero) to indicate "revoked", or 1 (one) to indicate not revoked.
                    type: integer
                    minimum: 0
                    maximum: 1
```
