### ISSUE TITLE
Should /credentials/verify require a vc in the request body?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#360]
Currently, the `verifiableCredential` property in the request body for `/credentials/verify` requests is not required (see [credential-verifier.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/credential-verifier.yml))

The schema should be modified to require a value for `verifiableCredential`.

Current Schema
```yaml
        schema:
          type: object
          properties:
            verifiableCredential:
              $ref: "../schemas/SerializedVerifiableCredential.yml"
```

Proposed Schema
```yaml
        schema:
          type: object
          required:
            - verifiableCredential
          properties:
            verifiableCredential:
              $ref: "../schemas/SerializedVerifiableCredential.yml"
```
