### ISSUE TITLE
Credential subject cannot be string

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#372]
The VC Data model specification [defines credentialSubject as an object or array (of objects)](https://www.w3.org/TR/vc-data-model/#credential-subject) having optional `id` properties.

Traceability interop should continue to restrict this to a single subject with required `id`, but MUST conform to the vc data model and not allow string values.

Modify the openapi schema and any relevant test suites to require that `credentialSubject` be an object with optional ID.

[Current Schema](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Credential.yml)
```yaml
  credentialSubject:
    oneOf:
      - type: string
      - type: object
        properties:
          id:
            description: The IRI identifying the Subject
            type: string
```

Proposed Schema:
```yaml
  credentialSubject:
    type: object
    properties:
      id:
        description: The IRI identifying the Subject
        type: string
```
