### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#41]
When errors occur, there should be helpful messages returned over http.

There should be an error message structure.

The structure should be used when handling 200 responses where the verification failed

There should also be a 400 error message structure, for cases where the client violates the api definition.

There should be test cases for errors, and each variant of an error.

There should be specific cases for revocation, expiration, preactivation.

**Comment by OR13** [comment]
We use a structure like this internally:

```
VerificationResult:
      title: Verification Check
      description: Verification result for a Verifiable Credential
      type: array
      items:
        type: object
        properties:
          status:
            type: string
            example: 'good'
          title:
            type: string
            example: 'Activation'
          description:
            type: string
            example: 'This credential activated a month ago'
```

Turning checks into readable sentences improves devx, and ui rendering consistency.

**Comment by OR13** [comment]
We need better error handling, we can't tell why things fail.

See https://github.com/w3c-ccg/vp-request-spec/pull/12

**Comment by nissimsan** [comment]
This is between the presenting parties: define happy path and sad path interactions. What are the 400 error we expect can occur? What are relevant error messages which will help resovle?

**Comment by nissimsan** [comment]
I might pick this up next time when I have better bandwidth.

**Comment by OR13** [comment]
awaiting https://github.com/w3c-ccg/vc-api/pull/258

**Comment by nissimsan** [comment]
next step: port over VC API error schemas, add postman for testing

**Comment by OR13** [comment]
Need to port over the schemas and write postman tests that produce errors for all documented error cases.

**Comment by OR13** [comment]
We still need to port over some error examples, ideally covering verify errors such as revocation.

**Comment by nissimsan** [comment]
Necessary for addressing this: 
- Make negative tests.
- Define error JSONs.

**Comment by OR13** [comment]
Use english language to describe error cases, then ensure that there is a postman collection that asserts the json structure for each error condition.

**Comment by mkhraisha** [comment]
Initial Error cases when issuing a credential:

requests:

- [ ] issuer that does not support suite required by options
- [ ] revocation type requested that is not supported by the issuer
- [ ] missing credential subject
- [ ] term not defined in context

responses:
- [ ] missing credential subject
- [ ] the credential subject is not an object or a string
- [ ] missing context
- [ ] missing proof
- [ ] missing credential status when the revocable credential was requested
- [ ] missing credential identifier when the revocable credential was requested
- [ ] signature type of proof does not match the requested suite
- [ ] issuance date is not present

**Comment by OR13** [comment]
We have a generic error response today:

```
type: object
required:
  - code
  - message
properties:
  code:
    type: integer
    format: int32
  message:
    type: string
  details:
    type: object
```
