### ISSUE TITLE
Credential allows empty `type` array

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#415]
The [vc data model](https://www.w3.org/TR/vc-data-model/#types) offers the following guidance regarding the `type` property of a credential:

> [Verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) and [verifiable presentations](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations) MUST have a type [property](https://www.w3.org/TR/vc-data-model/#dfn-property). That is, any [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) or [presentation](https://www.w3.org/TR/vc-data-model/#dfn-presentations) that does not have type [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is not [verifiable](https://www.w3.org/TR/vc-data-model/#dfn-verify), so is neither a [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) nor a [verifiable presentation](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-presentations).

additionally:

>The value of the type [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be, or map to (through interpretation of the `@context` property), one or more [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri). If more than one [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) is provided, the [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri) MUST be interpreted as an unordered set. Syntactic conveniences SHOULD be used to ease developer usage. Such conveniences might include JSON-LD terms. It is RECOMMENDED that each [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the type be one which, if dereferenced, results in a document containing machine-readable information about the type.

The current traceability-interop yaml specification for [`Credential.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Credential.yml) allows an empty array for the `type` property. This should be modified so that at least one element is required.

Current definition:
```yaml
  type:
    description: The Type of the Credential
    type: array
    items:
      type: string
```

Proposed definition:
```yaml
  type:
    description: The Type of the Credential
    type: array
    items:
      type: string
    minItems: 1
```
