### ISSUE TITLE
Require `type` property for embedded JSON-LD+LD proofs

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#417]
The [vc data model](https://www.w3.org/TR/vc-data-model/#proofs-signatures) states the following regarding embedded digital proofs:

> One or more cryptographic proofs that can be used to detect tampering and verify the authorship of a [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) or [presentation](https://www.w3.org/TR/vc-data-model/#dfn-presentations). The specific method used for an [embedded proof](https://www.w3.org/TR/vc-data-model/#dfn-embedded-proof) MUST be included using the type [property](https://www.w3.org/TR/vc-data-model/#dfn-property).

Right now, the traceability-interop openapi spec for [LinkedDataProof.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/LinkedDataProof.yml) specifies `type` as an optional element.

Current implementation:
```yaml
properties:
  type:
    type: string
    description: Linked Data Signature Suite used to produce proof.
    enum: ['Ed25519Signature2018', 'JsonWebSignature2020', 'jwt_vc']
...
```

Proposed implementation:
```yaml
required:
  - type
properties:
  type:
    type: string
    description: Linked Data Signature Suite used to produce proof.
    enum: ['Ed25519Signature2018', 'JsonWebSignature2020', 'jwt_vc']
...
```
